import type {Metadata} from 'next';
import LayoutComponent from '@/components/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return <LayoutComponent>{children}</LayoutComponent>;
};

export default Layout;
